package properties;

public enum ApplicationStrings {

	GMSEXECUTIONTEST_ERROR_MESSAGE_INSERT_EXECUTIONTEST,
	GMSEXECUTIONTEST_ERROR_MESSAGE_UPDATE_EXECUTIONTEST,
	GMSEXECUTIONTEST_ERROR_MESSAGE_DELETE_EXECUTIONTEST,
	GMSEXECUTIONTEST_ERROR_MESSAGE_LIST_ALL_EXECUTIONTEST,
	GMSEXECUTIONTEST_ERROR_MESSAGE_LIST_EXECUTIONTEST,
	
	GMSRESULT_ERROR_MESSAGE_INSERT_RESULT,
	GMSRESULT_ERROR_MESSAGE_UPDATE_RESULT,
	GMSRESULT_ERROR_MESSAGE_DELETE_RESULT,
	GMSRESULT_ERROR_MESSAGE_LIST_ALL_RESULT,
	GMSRESULT_ERROR_MESSAGE_LIST_RESULT,
	
	GMSTESTCASE_ERROR_MESSAGE_INSERT_TESTCASE,
	GMSTESTCASE_ERROR_MESSAGE_UPDATE_TESTCASE,
	GMSTESTCASE_ERROR_MESSAGE_DELETE_TESTCASE,
	GMSTESTCASE_ERROR_MESSAGE_LIST_ALL_TESTCASE,
	GMSTESTCASE_ERROR_MESSAGE_LIST_TESTCASE,
	
	GMSWORKFLOW_ERROR_MESSAGE_INSERT_TESTCASE,
	GMSWORKFLOW_ERROR_MESSAGE_UPDATE_TESTCASE,
	GMSWORKFLOW_ERROR_MESSAGE_DELETE_TESTCASE,
	GMSWORKFLOW_ERROR_MESSAGE_LIST_ALL_TESTCASE,
	GMSWORKFLOW_ERROR_MESSAGE_LIST_TESTCASE
}
