package properties;

public enum ApplicationStrings {

	GMSTESTCASE_ERROR_MESSAGE_INSERT_TESTCASE,
	GMSTESTCASE_ERROR_MESSAGE_UPDATE_TESTCASE,
	GMSTESTCASE_ERROR_MESSAGE_DELETE_TESTCASE,
	GMSTESTCASE_ERROR_MESSAGE_LIST_ALL_TESTCASE,
	GMSTESTCASE_ERROR_MESSAGE_LIST_TESTCASE,
	GMSWORKFLOW_ERROR_MESSAGE_INSERT_TESTCASE,
	GMSWORKFLOW_ERROR_MESSAGE_UPDATE_TESTCASE,
	GMSWORKFLOW_ERROR_MESSAGE_DELETE_TESTCASE,
	GMSWORKFLOW_ERROR_MESSAGE_LIST_ALL_TESTCASE,
	GMSWORKFLOW_ERROR_MESSAGE_LIST_TESTCASE
}
